"""add unique constraint votes card member

Revision ID: 3b9dd7fbe0a2
Revises: aa1bded4690f
Create Date: 2026-03-05 16:12:45.895083

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3b9dd7fbe0a2"
down_revision: Union[str, Sequence[str], None] = "aa1bded4690f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_vote_card_member", "votes", ["card_id", "member_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_vote_card_member", "votes", type_="unique")
    # ### end Alembic commands ###
