"""update trip_members nickname and session_token

Revision ID: aa1bded4690f
Revises: a74803d371d3
Create Date: 2026-03-05 15:52:01.957912

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aa1bded4690f"
down_revision: Union[str, Sequence[str], None] = "a74803d371d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trip_members", sa.Column("nickname", sa.String(length=255), nullable=False)
    )
    op.add_column("trip_members", sa.Column("session_token", sa.UUID(), nullable=False))
    op.create_index(
        op.f("ix_trip_members_session_token"),
        "trip_members",
        ["session_token"],
        unique=True,
    )
    op.create_unique_constraint(
        "uq_trip_member_nickname", "trip_members", ["trip_id", "nickname"]
    )
    op.drop_column("trip_members", "user_identifier")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trip_members",
        sa.Column(
            "user_identifier",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint("uq_trip_member_nickname", "trip_members", type_="unique")
    op.drop_index(op.f("ix_trip_members_session_token"), table_name="trip_members")
    op.drop_column("trip_members", "session_token")
    op.drop_column("trip_members", "nickname")
    # ### end Alembic commands ###
